
datadump.location:
 author: C:/Users/44746/big_data_app/authorDump.txt
 works: C:/Users/44746/big_data_app/worksDump.txt
 

spring:
 data:
  cassandra:
   keyspace-name: main
   username: StZByJoNLuNvueJoFvdsUKNg
   password: rAyu+,olT2epkYIr_DPT1ZeFX3adiYvq,a7J67rAxNMGZ96WOmpNABP0g46hBAdw8qd1GiwRRdHIQKYPi.nM.LHAb3iJxpHebyOtpQNCS8yoBe1h,G,fSKL7N1xe4Tj-
   #schema action is the cassandra equivalent to what hibernate does- we create the entity and that gets converted to a table in SQL- this does that for Cassandra
   #in hybernate it was update/create, create if does not exists does what it says 
   schema-action: create-if-not-exists
   #configuring request timeout - give it time to be able to connect - try for 10s 
   request: 
    timeout: 10s
   connection:
    connect-timeout: 10s
    init-query-timeout: 10s #may not need this 
 main:
  allow-circular-references: true
 
   
datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip #the bundle downloaded from datastax 
  
#found on astra datastax
astra.db:
 id: cd8d1e3f-abf5-4fdb-a715-6bfed945e67d-1
 region: us-east1
 keyspace: main
 application.token: AstraCS:StZByJoNLuNvueJoFvdsUKNg:7e1f5f0af87ed69301bd2542ca5dc501261e03c288febf3f00118b58f8c4c732
